###
# Call the function to built the chart when the template is rendered
###

###
# Function to draw the column chart
###

builtColumn = (BarData) ->
  $('#container-column').highcharts
    chart: type: 'column'
    title: text: 'Monthly Red Bars Bike Rides'
    colors: [
      '#00A9E0'
      '#3B3B3D'
      '#67CDDC'
      '#98C73D'
      '#D0DD2B'
    ]
    subtitle: text: 'Source: Math.random()'
    credits: enabled: false
    xAxis: categories: [
      'Jan'
      'Feb'
      'Mar'
      'Apr'
      'May'
      'Jun'
      'Jul'
      'Aug'
      'Sep'
      'Oct'
      'Nov'
      'Dec'
    ]
    yAxis:
      min: 0
      title: text: 'Bikes Ridden'
    tooltip:
      headerFormat: '<h4>{point.key}</h4>'
      shared: true
      useHTML: true
    plotOptions: column:
      pointPadding: 0.2
      borderWidth: 0
    series: BarData
  return

Template.columnDemo.rendered = ->
  Meteor.subscribe 'AdminBarChartData', ->
    if Meteor.isClient
      BarData = AdminBarChart.find().fetch()
      # console.log(BarData);
      builtColumn BarData
    return

# ---
# generated by js2coffee 2.0.4