###
# Call the function to built the chart when the template is rendered
###

###
# Function to draw the pie chart
###

builtPieUsers = ->
  # 'external' data
  dataUsers = new Array
  dataUsers.push
    name: 'Under 5 rides/week'
    y: _.random(10, 1000)
    color: '#32742C'
  dataUsers.push
    name: '5 -  30 rides/week'
    y: _.random(10, 1000)
    color: '#D0D102'
  dataUsers.push
    name: '30+ rides/week'
    y: _.random(10, 1000)
    color: '#61AE24'
  $('#container-pie-users').highcharts
    chart:
      plotBackgroundColor: null
      plotBorderWidth: null
      plotShadow: false
    title: text: 'Users by Number of Rides'
    credits: enabled: false
    tooltip: pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    plotOptions: pie:
      allowPointSelect: true
      cursor: 'pointer'
      dataLabels: enabled: false
      showInLegend: true
    series: [ {
      type: 'pie'
      name: 'Users'
      data: dataUsers
    } ]
  return

Template.pieDemoUsers.rendered = ->
  builtPieUsers()
  return

# ---
# generated by js2coffee 2.0.4