if Meteor.isClient
  Template.pics.helpers photo: ->
    Session.get 'photo'
  Template.pics.events 'click button': ->
    cameraOptions =
      width: 800
      height: 600
    MeteorCamera.getPicture cameraOptions, (error, data) ->
      Session.set 'photo', data
      return
    return

# ---
# generated by js2coffee 2.0.4