Template.LoginFormCD.rendered = ->
  $form_modal = $('.cd-user-modal')
  $form_login = $form_modal.find('#cd-login')
  $form_signup = $form_modal.find('#cd-signup')
  $form_forgot_password = $form_modal.find('#cd-reset-password')
  $form_modal_tab = $('.cd-switcher')
  $tab_login = $form_modal_tab.children('li').eq(0).children('a')
  $tab_signup = $form_modal_tab.children('li').eq(1).children('a')
  $forgot_password_link = $form_login.find('.cd-form-bottom-message a')
  $back_to_login_link = $form_forgot_password.find('.cd-form-bottom-message a')
  $main_nav = $('.main-nav')
  #open modal

  login_selected = ->
    $form_login.addClass 'is-selected'
    $form_signup.removeClass 'is-selected'
    $form_forgot_password.removeClass 'is-selected'
    $tab_login.addClass 'selected'
    $tab_signup.removeClass 'selected'
    return

  signup_selected = ->
    $form_login.removeClass 'is-selected'
    $form_signup.addClass 'is-selected'
    $form_forgot_password.removeClass 'is-selected'
    $tab_login.removeClass 'selected'
    $tab_signup.addClass 'selected'
    return

  forgot_password_selected = ->
    $form_login.removeClass 'is-selected'
    $form_signup.removeClass 'is-selected'
    $form_forgot_password.addClass 'is-selected'
    return

  $main_nav.on 'click', (event) ->
    if $(event.target).is($main_nav)
      # on mobile open the submenu
      $(this).children('ul').toggleClass 'is-visible'
    else
      # on mobile close submenu
      $main_nav.children('ul').removeClass 'is-visible'
      #show modal layer
      $form_modal.addClass 'is-visible'
      #show the selected form
      if $(event.target).is('.cd-signup') then signup_selected() else login_selected()
    return
  #close modal
  $('.cd-user-modal').on 'click', (event) ->
    if $(event.target).is($form_modal) or $(event.target).is('.cd-close-form')
      $form_modal.removeClass 'is-visible'
    return
  #close modal when clicking the esc keyboard button
  $(document).keyup (event) ->
    if event.which == '27'
      $form_modal.removeClass 'is-visible'
    return
  #switch from a tab to another
  $form_modal_tab.on 'click', (event) ->
    event.preventDefault()
    if $(event.target).is($tab_login) then login_selected() else signup_selected()
    return
  #hide or show password
  $('.hide-password').on 'click', ->
    $this = $(this)
    $password_field = $this.prev('input')
    if 'password' == $password_field.attr('type') then $password_field.attr('type', 'text') else $password_field.attr('type', 'password')
    if 'Hide' == $this.text() then $this.text('Show') else $this.text('Hide')
    #focus and move cursor to the end of input field
    $password_field.putCursorAtEnd()
    return
  #show forgot-password form
  $forgot_password_link.on 'click', (event) ->
    event.preventDefault()
    forgot_password_selected()
    return
  #back to login from the forgot-password form
  $back_to_login_link.on 'click', (event) ->
    event.preventDefault()
    login_selected()
    return
  #REMOVE THIS - it's just to show error messages
  $form_login.find('input[type="submit"]').on 'click', (event) ->
    event.preventDefault()
    $form_login.find('input[type="email"]').toggleClass('has-error').next('span').toggleClass 'is-visible'
    return
  $form_signup.find('input[type="submit"]').on 'click', (event) ->
    event.preventDefault()
    $form_signup.find('input[type="email"]').toggleClass('has-error').next('span').toggleClass 'is-visible'
    return
  #IE9 placeholder fallback
  #credits http://www.hagenburger.net/BLOG/HTML5-Input-Placeholder-Fix-With-jQuery.html
  if !Modernizr.input.placeholder
    $('[placeholder]').focus(->
      input = $(this)
      if input.val() == input.attr('placeholder')
        input.val ''
      return
    ).blur(->
      input = $(this)
      if input.val() == '' or input.val() == input.attr('placeholder')
        input.val input.attr('placeholder')
      return
    ).blur()
    $('[placeholder]').parents('form').submit ->
      $(this).find('[placeholder]').each ->
        input = $(this)
        if input.val() == input.attr('placeholder')
          input.val ''
        return
      return
  return
#credits http://css-tricks.com/snippets/jquery/move-cursor-to-end-of-textarea-or-input/

jQuery.fn.putCursorAtEnd = ->
  @each ->
    # If this function exists...
    if @setSelectionRange
      # ... then use it (Doesn't work in IE)
      # Double the length because Opera is inconsistent about whether a carriage return is one character or two. Sigh.
      len = $(this).val().length * 2
      @setSelectionRange len, len
    else
      # ... otherwise replace the contents with itself
      # (Doesn't work in Google Chrome)
      $(this).val $(this).val()
    return

# ---
# generated by js2coffee 2.1.0