# # Example Code:
# @encrypted = CryptoJS.AES.encrypt('Message', 'Dinosaurs')
# console.log encrypted.toString()
# # 53616c7465645f5fe5b50dc580ac44b9be85d240abc5ff8b66ca327950f4ade5
# @decrypted = CryptoJS.AES.decrypt(encrypted, 'Dinosaurs')
# console.log decrypted.toString(CryptoJS.enc.Utf8)
# # Message
# # AES Library: http://forum.arduino.cc/index.php?topic=88890.0
# # here are three hex IDs:
# # {0xFD, 0xBB, 0x84, 0x9A},
# # {0xE4, 0xDD, 0x05, 0x0F},
# # {0x93, 0x24, 0xBE, 0xA9}
# # Alternative Meteor Package: https://atmospherejs.com/altapp/aes
# # Experimenting with hex keys
# stuff = [
#   0xF3
#   0x44
#   0x81
#   0xEC
# ]
# console.log stuff
# control = [
#   0xF3
#   0x44
#   0x81
#   0xEC
# ]
# if stuff == control
#   console.log 'true'
# else
#   console.log 'false'
#   test = stuff - control
#   console.log test

# # ---
# # generated by js2coffee 2.0.4