###
# Call the function to built the chart when the template is rendered
###

#  if(Meteor.isClient) {
#     Meteor.subscribe("AdminAreaChartData");
# }
# if(Meteor.isClient) {
#     Session.set("current_channel", "cool_people_channel");
#     Meteor.autorun(function() {
#         Meteor.subscribe("messages", Session.get("current_channel"));
#     });
# }

###
# Function to draw the area chart
###

builtArea = (randArray1, randArray2) ->
  $('#container-area').highcharts
    chart:
      type: 'area'
      animation: Highcharts.svg
    title: text: 'Bike Quantities'
    credits: enabled: false
    colors: [
      '#98C73D'
      '#3B3B3D'
      '#00A9E0'
    ]
    xAxis: categories: [
      'Jan'
      'Feb'
      'Mar'
      'Apr'
      'May'
      'Jun'
      'Jul'
      'Aug'
      'Sep'
      'Oct'
      'Nov'
      'Dec'
    ]
    yAxis: title: text: 'Milieage (miles)'
    tooltip: pointFormat: '{series.name} <b>{point.y:,.0f}</b> miles'
    series: [
      {
        name: 'Bikes Ridden'
        data: randArray1
      }
      {
        name: 'Miles Redistributed'
        data: randArray2
      }
    ]
  return

Template.areaDemo.created = ->
  Meteor.subscribe 'AdminAreaChartData', ->
    if Meteor.isClient
      # console.log(BarData);
      randArray1 = []
      _.times 12, ->
        randArray1.push _.random(100, 800)
        return
      randArray2 = []
      _.times 12, ->
        randArray2.push _.random(1, 200)
        return
      builtArea randArray1, randArray2
    return

# ---
# generated by js2coffee 2.0.4