###*******************************************###

###   Remove Below content for Production          ###

###******************************************###

Meteor.publish 'RFIDdataInfo', ->
  RFIDdata.find()

# ---
# generated by js2coffee 2.0.4