# isMobile =
#   Android: ->
#     navigator.userAgent.match /Android/i
#   BlackBerry: ->
#     navigator.userAgent.match /BlackBerry/i
#   iOS: ->
#     navigator.userAgent.match /iPhone|iPad|iPod/i
#   Opera: ->
#     navigator.userAgent.match /Opera Mini/i
#   Windows: ->
#     navigator.userAgent.match /IEMobile/i
#   any: ->
#     isMobile.Android() or isMobile.BlackBerry() or isMobile.iOS() or isMobile.Opera() or isMobile.Windows()

# Template.about.rendered = ->
#   # var typedStrings = [" better"];
#   # jQuery(function($) {
#   #     if (!isMobile.any()) {
#   #       var typedStrings = [" better"];
#   #       $('#is-mobile').toggleClass('show hide');
#   #     }
#   #     if (isMobile.any()) {
#   #       var typedStrings = [" faster", " smarter", " cheaper", " better"];
#   #       $('#is-desktop').toggleClass('show hide');
#   #     }
#   # });
#   # such Wow.js animatinos for explanation section
#   (new WOW).init()
#   # Typed.js demo -> outputs text for title
#   $ ->
#     `var typedStrings`
#     if !isMobile.any()
#       # Is non-mobile device
#       typedStrings = [
#         ' faster'
#         ' smarter'
#         ' cheaper'
#         ' better'
#       ]
#     if isMobile.any()
#       # Is mobile device
#       typedStrings = [ ' better' ]
#     $('.typed-element').typed
#       strings: typedStrings
#       typeSpeed: 150
#       startDelay: 300
#       backDelay: 500
#     return

#   ###!
#   # Start Bootstrap - Agency Bootstrap Theme (http://startbootstrap.com)
#   # Code licensed under the Apache License v2.0.
#   # For details, see http://www.apache.org/licenses/LICENSE-2.0.
#   ###

#   # jQuery for page scrolling feature - requires jQuery Easing plugin
#   $ ->
#     $('a.page-scroll').bind 'click', (event) ->
#       $anchor = $(this)
#       $('html, body').stop().animate { scrollTop: $($anchor.attr('href')).offset().top }, 1500, 'easeInOutExpo'
#       event.preventDefault()
#       return
#     return
#   # // Highlight the top nav as scrolling occurs
#   # $('body').scrollspy({
#   #     target: '.navbar-fixed-top'
#   # });
#   # Closes the Responsive Menu on Menu Item Click
#   $('.navbar-collapse ul li a').click ->
#     $('.navbar-toggle:visible').click()
#     return
#   return

# # ---
# # generated by js2coffee 2.0.4