# Global Route Configuration
Router.configure
  loadingTemplate: 'loading'
  notFoundTemplate: 'notFound'
  layoutTemplate: 'appLayout'
# Plugins
Router.plugin 'dataNotFound', dataNotFoundTemplate: 'notFound'
Router.plugin 'ensureSignedIn', except: [
  'about'
  'atSignIn'
  'atSignUp'
  'atForgotPassword'
  'progress'
]
# Sign out and go to home page with route control
# Useful, from: http://stackoverflow.com/questions/27743660/proper-syntax-for-iron-routers-router-route
Router.route '/sign-out', (->
),
  name: 'signOut'
  onBeforeAction: ->
    if Meteor.userId()
      Meteor.logout()
    @next()
    return
  onAfterAction: ->
    Router.go '/'
    return

###   Public ###

Router.route '/', name: 'about'

### User ###

Router.route '/student'
Router.route '/map', layoutTemplate: 'fullLayout'

### Administrator ###

Router.route '/dashboard'
Router.route '/users'
Router.route '/charts', name: 'chartsAdmin'
Router.route '/RFIDlayout'
Router.route '/mechanicView'
Router.route '/mechmap'
Router.route '/timeseries'
Router.route '/admin2layoutAllData',
  waitOn: ->
    Meteor.subscribe 'TestUsersData'
  data: ->
    TestUsers.find {}, limit: 20
Router.route '/admin2layoutBikeData/:_id',
  name: 'admin2layoutBikeData'
  waitOn: ->
    Meteor.subscribe 'TestUsersData'
  data: ->
    TestUsers.findOne @params._id
Router.route '/admin3layoutAllData',
  name: 'admin3layoutAllData'
  waitOn: ->
    Meteor.subscribe 'TimeSeriesData'
  data: ->
    TimeSeries.find {}, limit: 20
Router.route '/admin3layoutBikeData/:_id',
  name: 'admin3layoutBikeData'
  waitOn: ->
    Meteor.subscribe 'TimeSeriesData'
  data: ->
    TimeSeries.findOne @params._id

###*******************************************###

###   WIP - Test Routes                       ###

###******************************************###

Router.route '/progress'
Router.route '/agency'
# /*********************************************/
# /*   Remove Below content for Production     */
# /********************************************/
# // For testing loading page with no wait time
# // Todo: Integrate more seamlessly into app
# Router.route('/loading');
# Router.route '/webix', layoutTemplate: 'fullLayout'

# ---
# generated by js2coffee 2.0.4