# Source: http://stackoverflow.com/questions/604167/how-can-we-access-the-value-of-a-radio-button-using-the-dom

getRadioValue = (theRadioGroup) ->
  elements = document.getElementsByName(theRadioGroup)
  i = 0
  l = elements.length
  while i < l
    if elements[i].checked
      # console.log(elements[i].value);
      return elements[i].value
    i++
  return

Meteor.subscribe 'bikesData'
Meteor.subscribe 'RandMechanicNamesData'

Template.bikesList.created = ->
  # Default to all users view
  Session.set 'BikeNumber', 1
  Session.set 'sortType', 'timestamp'
  Session.set 'sortOrder', 'desc'
  Session.set 'mechanic', ''
  return

Template.bikesList.helpers sortType: [
  'timestamp'
  'status'
  'mechanicNotes'
  'partslist'
  'mechanic'
  'role'
  'lat'
  'lng'
]
Template.bikesList.events 'submit form': (event) ->
  event.preventDefault()
  BikeNumber = parseFloat(event.target.BikeNumber.value)
  Session.set 'BikeNumber', BikeNumber
  # console.log(_.isString(BikeNumber));
  # var sortOrder = event.target.sortOrder;
  Session.set 'sortOrder', getRadioValue('sortOrder')
  # console.log(getRadioValue('sortOrder'));
  Session.set 'sortType', event.target.sortType.value
  Session.set 'mechanic', event.target.mechanicSelected.value
  console.log 'mechanic = ' + event.target.mechanicSelected.value
  # bikes.call();
  return
# Tracker.autorun(function () {
Template.bikesList.helpers bikes: ->
  if Bikes.findOne(bike: Session.get('BikeNumber'))
    # this helper returns a cursor of all of the posts in the collection
    bikeData = Bikes.findOne(bike: Session.get('BikeNumber')).updates
    # Return only specific mechanic
    if Session.get('mechanic')
      bikeData = _.filter(bikeData, (bikes) ->
        bikes.mechanic == Session.get('mechanic')
      )
    else
      console.log 'No Session'
    # Order results for table (desc vs. asc)
    if Session.get('sortOrder') == 'desc'
      # console.log(bikeData);
      return _.sortBy(bikeData, Session.get('sortType')).reverse()
    else
      return _.sortBy(bikeData, Session.get('sortType'))
  return
# });
Template.bikesList.helpers mechanicName: ->
  if RandMechanicNames.findOne()
    # this helper returns a cursor of all of the posts in the collection
    mechanics = RandMechanicNames.findOne().staff
    # console.log(_.sortBy(mechanics, 'name'));
    return _.sortBy(mechanics, 'name')
  return

# ---
# generated by js2coffee 2.0.4