Meteor.methods 'loop': (dataSet, schema) ->
  # Print out schema of received data]
  # for (var key in dataSet) {
  #   if (dataSet.hasOwnProperty(key)) {
  #     console.log(key + " -> " + dataSet[key]);
  #   }
  # }
  # Prepare fields to udpate MongoDB
  fields = {}
  root = [ 'Time.' + dataSet.timeHH + '.' + dataSet.timemm ]
  fields[root + '.user'] = dataSet.User
  fields[root + '.lat'] = dataSet.Lat
  fields[root + '.lng'] = dataSet.Long
  # Update MongoDB data based on bike number
  record = TimeSeries.findOne(
    Bike: dataSet.BikeNumber
    YYYY: dataSet.timeYYYY
    MM: dataSet.timeMM
    DD: dataSet.timeDD)
  TimeSeries.update record, $set: fields
  'ok'
Meteor.methods 'current': (dataSet, schema) ->
  # Print out schema of received data]
  for key of dataSet
    if dataSet.hasOwnProperty(key)
      console.log key + ' -> ' + dataSet[key]
  # Prepare fields to udpate MongoDB
  fields = {}
  fields.lat = dataSet.lat
  fields.lng = dataSet.lng
  # Update MongoDB data based on bike number
  record = Current.findOne(Bike: dataSet.BikeNumber)
  Current.update record, $set: fields
  'ok'
Meteor.methods 'chart': (dataSet) ->
  # Prepare fields to udpate MongoDB
  fields = {}
  fields['data.' + dataSet.BikeNumber] = dataSet.Potentiometer
  fields.x = dataSet.x
  console.log dataSet.Potentiometer
  # Update MongoDB data based on bike number
  record = AdminAreaChart.findOne()
  AdminAreaChart.update record, $set: fields
  'ok'

# ---
# generated by js2coffee 2.0.4