# # Meteor.call('mySubmitFunc');
# @UsersController = AppController.extend(
#   waitOn: ->
#     @subscribe 'usersInfo'
#   data: users: Meteor.users.find({})
#   onAfterAction: ->
#     Meta.setTitle 'Users'
#     return
# )

# # ---
# # generated by js2coffee 2.0.4